name: Eleventy Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: mkdir -p ~/.ssh/
      - run: echo "${{secrets.DEPLOY_KEY}}" > ~/.ssh/id_rsa
      - run: chmod 600 ~/.ssh/id_rsa
      - run: cat ~/.ssh/id_rsa
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: git config --global user.name "someone"
      - run: git config --global user.email "someone@somewhere"
      # run: git remote -v
      - run: npm install
      - run: npm install -g @11ty/eleventy
      # run: npm install -g gh-pages@2.0.1
      - run: eleventy --pathprefix="/workflows-11ty/"
      # run: ls -lah _site
      # run: gh-pages --dotfiles --message "Updates" --dist _site
      - run: pwd
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
