name: Eleventy Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to master
      uses: actions/checkout@v2
    - name: Set up NodeJS 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - name: Install and Configure Dependencies
      run: |
        npm install
        npm install -g @11ty/eleventy
    - name: Generate Eleventy Static Files
      run: |
        eleventy --pathprefix="/workflows-11ty/"
    - name: Deploy Static Files to gh-pages Branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
